### ISSUE TITLE
No controllers installed

### ISSUE THREAD

**Issue by Mikekij** [TwoFactorAuth/ruby#5]
I followed the installation instructions in the readme, but the app is throwing a:

    undefined method `two_factor_auth_registration'

error. Doesn't look like anything but the migration was installed. Any suggestions?

**Comment by Mikekij** [comment]
To clarify, I see the gem installed in my .rvm gems directory, but running "rake routes" in my app shows no routes associated with TwoFactorAuth.

**Comment by pushcx** [comment]
I dug into the bug this morning. First, you're missing the `two_factor_for :users` in `config/routes.rb` because the `two_factor_auth:install` route failed to add it. You can do that by hand now, or I'll push a new release when I finish the rest of this bug.

The gem wasn't originally using a namespaced engine, and that isolation (while vital for avoiding conflicts with app code) seems to have hidden the helpers and controllers away completely. I'm going to keep tinkering until I find the right `require` incantation to make them available to your Rails app code.

**Comment by Mikekij** [comment]
Thanks @pushcx . I'll give this a shot Tuesday morning.

**Comment by pushcx** [comment]
I've tagged and pushed a new version with more install docs and a fix for your bug. I'm sorry you ran into it, and please don't hesitate to reopen this issue or file more if you have any more trouble.
